# Generated by Django 4.2 on 2025-12-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('IN_KITCHEN', 'In Kitchen'), ('SERVED', 'Served')], default='PLACED', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
