# Generated by Django 4.2 on 2025-12-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('NOT_GENERATED', 'Not Generated'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid')], max_length=20)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
            ],
        ),
    ]
