# Generated by Django 4.2 on 2025-12-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('seating_capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('BILL_REQUESTED', 'Bill Requested'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
